name: build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libeigen3-dev libgtest-dev libginac-dev
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install numpy
          pip install matplotlib
      - name: Build & Test
        working-directory: ${{github.workspace}}
        run: |
          JOBS=$(($(grep cpu.cores /proc/cpuinfo | sort -u | sed 's/[^0-9]//g') + 1))
          cmake -S . -B build -DBUILD_EXAMPLES=ON -DBUILD_TESTS=ON
          cmake --build build -j${JOBS}
          cd build
          ctest
      
