name: build

on:
  push:
    branches:
      - main
      - develop
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt install libeigen3-dev libgtest-dev
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install numpy
          pip install matplotlib
      - name: Build & Test
        working-directory: ${{github.workspace}}
        run: |
          cmake -S . -B build
          cmake --build build
          sudp cmake --install build
          cd build
          ctest
      