name: documentation

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install python library
        run: pip3 install mkdocs mkdocs-exclude mkdocs-material fontawesome_markdown markdown-katex

      - name: Install Doxygen 
        run: |
          sudo　apt install doxygen
          wget https://github.com/matusnovak/doxybook2/releases/download/v1.5.0/doxybook2-linux-amd64-v1.5.0.zip
          sudo　unzip doxybook2-linux-amd64-v1.5.0.zip -d /usr

      - name: mkdocs build
        run: |
          mkdocs build

      - name: mkdocs deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./site